### ISSUE TITLE
Ignores grant this user elevated privilages command

### ISSUE THREAD

**Issue by chri55mith** [mkdo/cpd-theme#1]
When I un-tick Grant this user elevated admin privileges, and save, it ignores me and I still have elevated admin privileges.

**Comment by mwtsn** [comment]
Hi Chris,

Thanks for reporting this issue. I have now fixed it so that elevated users can remove the elevated privileges of other elevated users (patched in 2.4.7).

However, an elevated user cannot remove their own elevated status. This is so there will always be at least one elevated user within the site.

Without having a single elevated user on the site, there is a risk that a team could lock them out of the sites advanced features. 

I hope this helps.
